### ISSUE TITLE
Spec: Add participant properties

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/digitallinguistics.github.io#34]
We have a `participant` object, but the Spec doesn't yet have items for the attributes of the participant object. Add specifications to for the `"name"`, `"role"`, and '"personID"` attributes of the participant.

**Comment by dwhieb** [comment]
You'll want to make a new branch (JohnSpecEdits or some such) while you're working, then make a pull request when you're done so we can review.

Be sure to increment the version number and date when you start making edits (only need to increment once per day per person or work session, not for every little change you make.)

**Comment by dwhieb** [comment]
Text to use for these attributes:
* *name* - The name of this participant.
* *roles* - The role that this person played in the creation or curation of this text, e.g. speaker, translator, transcriber, rehearer, editor, checker, glosser, researcher, etc.
* *personID* - The unique ID for this person, or reference to the JSON object for this person.

**Comment by dwhieb** [comment]
@amundo @jmangel
* Do you think it should be `role` or `roles`? [I can go either way.]
* Should the list of possible roles be open-ended, or should we create a predefined set? [I can go either way.]
* Should we add a pseudonym field? [I think we should]
* Should we add an initials field? [I think it'd be helpful]

Some other thoughts:
I think the participant object should contain the minimum amount of data that you need to be able to pass the text to someone as a standalone JSON file, without having to look up more details about the person. In fact, the benefit of this is that it allows you to intentionally conceal additional details about the person for the purpose of anonymity. If you want, you can provide a name or pseudonym for the person in the text file, but then don't include any person files with it (since the person JSON object is where the personal details of that individual will live).

**Comment by jmangel** [comment]
Closed with merge #59
