### ISSUE TITLE
Create the DLX Interlinear Text Format Specification page

### ISSUE THREAD

**Issue by jmangel** [digitallinguistics/digitallinguistics.github.io#51]
<a href="https://github.com/dwhieb"><img src="https://avatars.githubusercontent.com/u/5892997?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dwhieb](https://github.com/dwhieb)**
_Wednesday Feb 04, 2015 at 05:55 GMT_
_Originally opened as https://github.com/digitallinguistics/core/issues/23_

----

Steal the layout of the geoJSON specification.

**Comment by jmangel** [comment]
<a href="https://github.com/dwhieb"><img src="https://avatars.githubusercontent.com/u/5892997?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dwhieb](https://github.com/dwhieb)**
_Monday Feb 16, 2015 at 01:28 GMT_

----

This should be an actual HTML page, based on what's currently on our [Data Map](https://github.com/digitallinguistics/core/wiki/Data-Map) page on the wiki.

**Comment by amundo** [comment]
Done at http://digitallinguistics.github.io/spec/
