### ISSUE TITLE
Add console Wugbot

### ISSUE THREAD

**Issue by amundo** [digitallinguistics/digitallinguistics.github.io#7]
Add a console ASCII Wubgot to the front page of wugbot.org, like Facebook's freakout console message or https://developer.mozilla.org .

**Comment by dwhieb** [comment]
I'm a little confused - what's a console. ASCII Wugbot? @amundo @wugology

**Comment by wugology** [comment]
It's ASCII art, so that anyone who tries to poke under the hood by clicking "view source" on our website will be greeted by an ascii wug bot.
